Permission.create(:klass => "ProjectsController", :action => "index")
Permission.create(:klass => "ProjectsController", :action => "show")
Permission.create(:klass => "TasksController", :action => "index")
Permission.create(:klass => "TasksController", :action => "show")
Permission.create(:klass => "RolesController", :action => "index")
Permission.create(:klass => "RolesController", :action => "show")
Permission.create(:klass => "RolesController", :action => "edit")